from __future__ import annotations

from typing import Any, List, Optional, Protocol, Tuple, runtime_checkable

# A locator is a Selenium-style (By.X, "selector") tuple. Kept framework-neutral
# here; concrete drivers translate it to their own find mechanism.
Locator = Tuple[str, str]


@runtime_checkable
class ElementHandle(Protocol):
    """Framework-agnostic handle to a single page element.

    Concrete drivers (Selenium today, Playwright/Appium later) return objects that
    satisfy this protocol so page objects never touch a framework's element type.
    """

    def click(self) -> None: ...

    def clear(self) -> None: ...

    def send_keys(self, text: str) -> None: ...

    def get_attribute(self, name: str) -> Optional[str]: ...

    @property
    def text(self) -> str: ...

    def is_selected(self) -> bool: ...

    def is_enabled(self) -> bool: ...

    def is_displayed(self) -> bool: ...


@runtime_checkable
class BaseDriver(Protocol):
    """Framework-agnostic browser driver.

    The common automation path (navigate / find / wait / interact / screenshot /
    url) is abstracted here so page objects do not depend on a concrete framework.
    ``execute_script`` and ``raw`` are explicit Selenium-only escape hatches; a
    non-Selenium backend may raise ``NotImplementedError`` for them.
    """

    def get(self, url: str) -> None: ...

    def find(self, locator: Locator) -> ElementHandle: ...

    def find_all(self, locator: Locator) -> List[ElementHandle]: ...

    def wait_for_present(self, locator: Locator, timeout: int) -> ElementHandle: ...

    def wait_for_visible(self, locator: Locator, timeout: int) -> ElementHandle: ...

    def wait_for_clickable(self, locator: Locator, timeout: int) -> ElementHandle: ...

    def wait_for_text(self, locator: Locator, text: str, timeout: int) -> bool: ...

    def wait_for_invisible(self, locator: Locator, timeout: int) -> bool: ...

    def wait_for_page_loaded(self, locator: Locator, timeout: int) -> None: ...

    def wait_for_url_change(self, original_url: str, timeout: int) -> bool: ...

    def wait_for_url_contains(self, substring: str, timeout: int) -> bool: ...

    def execute_script(self, script: str, *args: Any) -> Any: ...

    def accept_alert(self, timeout: int) -> None: ...

    def save_screenshot(self, path: str) -> bool: ...

    def refresh(self) -> None: ...

    def back(self) -> None: ...

    @property
    def current_url(self) -> str: ...

    @property
    def raw(self) -> Any: ...

    def quit(self) -> None: ...
