services:
  testopus:
    # Use the image we just built with docker/build-push-action
    image: testopus:latest
    container_name: testopus
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app
      - DOCKER_ENV=true
    command: test:run
    shm_size: 2gb  