services:
  testopus:
    # Use the image we just built with docker/build-push-action
    image: testopus:latest
    container_name: testopus
    volumes:
      - ..:/app:delegated
    environment:
      - PYTHONPATH=/app
      - DOCKER_ENV=true
      - PYTEST_ADDOPTS=--verbose
    # Run with appropriate flags for Allure reporting
    command: --verbose -vv --alluredir=/app/reports/allure-results --html=/app/reports/html/report.html --self-contained-html /app/tests
    shm_size: 2gb  