services:
  testopus:
    # Use the image we just built with docker/build-push-action
    image: testopus:latest
    container_name: testopus
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app
      - DOCKER_ENV=true
    # Run with appropriate flags for Allure reporting
    command: --alluredir=reports/allure-results --html=reports/html/report.html tests
    shm_size: 2gb  